const express = require('express')
const app = express()
const connect=require('./mongo.config')
const ProductRouter=require('./router/productRouter')
app.use(express.json())
app.use('/product',ProductRouter)
app.get('/sujan',(req,res)=>{
    res.send('suju babayS')
})
app.listen(8000,()=>console.log('server is running'))